services:
    Sidus\DataGridBundle\Renderer\ColumnValueRendererInterface:
        alias: Sidus\DataGridBundle\Renderer\DefaultColumnValueRenderer

    Sidus\DataGridBundle\Renderer\DefaultColumnValueRenderer:
        autowire: true
        public: false

    Sidus\DataGridBundle\Renderer\ColumnLabelRendererInterface:
        alias: Sidus\DataGridBundle\Renderer\DefaultColumnLabelRenderer

    Sidus\DataGridBundle\Renderer\DefaultColumnLabelRenderer:
        autowire: true
        public: false
